img_size: 224
audio_length: 1024
patch_size: 16
in_chans: 3
embed_dim: 768
modality_specific_depth: 11
num_heads: 12
decoder_embed_dim: 512
decoder_depth: 8
decoder_num_heads: 16
mlp_ratio: 4.
norm_pix_loss: False
tr_pos: False
